### ISSUE TITLE
quickstart.sh fails to find develop branch for predix-scripts repos

### ISSUE THREAD

**Issue by j12y** [PredixDev/predix-machine-template-adapter-edison#1]
It appears that you are looking for a **develop** branch:
https://github.com/PredixDev/predix-machine-template-adapter-edison/blob/master/quickstart.sh#L96

but there does not appear to be one in that repos:
https://github.com/PredixDev/predix-scripts/branches

This is encountered when following the edison instructions here:
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1742&tag=1752&journey=Setup%20Intel%20Edison%20for%20Predix&resources=1785,1739,1742,1743

```
$ ./quickstart.sh -i edge -b master
git clone https://github.com/PredixDev/predix-scripts.git -b develop --depth 1
Cloning into 'predix-scripts'...
warning: Could not find remote branch develop to clone.
fatal: Remote branch develop not found in upstream origin
```

**Comment by turnerth** [comment]
should be fixed.
