### ISSUE TITLE
quickstart.sh fails to access internal github repository

### ISSUE THREAD

**Issue by j12y** [PredixDev/predix-machine-template-adapter-edison#2]
When using the master branch for #1 it appears to be a dependency on an internal enterprise github:
https://github.com/PredixDev/predix-scripts/blob/master/scripts/variables.sh#L59

Possibly this is what it should be in order to work for all developers:
https://github.com/PredixDev/Predix-HelloWorld-WebApp

Here is example output:
```
##################################### Creating Predix Services #####################################
Cloning into 'edge-hello-world'...
fatal: unable to access 'https://github.build.ge.com/adoption/Predix-HelloWorld-WebApp.git/': Could not resolve host: github.build.ge.com
```
There are a few other repos referenced as well.

This comes from following this tutorial:
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1742&tag=1752&journey=Setup%20Intel%20Edison%20for%20Predix&resources=1785,1739,1742,1743

**Comment by turnerth** [comment]
should be fixed.

**Comment by vrathna** [comment]
This issue is occurring again since this Tuesday
